### ISSUE TITLE
iOS Safari font-size on homepage

### ISSUE THREAD

**Issue by zgreen** [zgreen/MITlibraries-parent#8]
The "What Am I Searching" accordion has strange font-size behavior on multiple versions of iOS Safari.
![photo 1](https://f.cloud.github.com/assets/1700355/1881284/c1f07ab0-7964-11e3-86c2-48fb3a50a2b0.PNG)
![photo 2](https://f.cloud.github.com/assets/1700355/1881285/c1f1db08-7964-11e3-8bdd-6514c904fbab.PNG)
![photo 3](https://f.cloud.github.com/assets/1700355/1881286/c1f27478-7964-11e3-847d-3d6b764dde5c.PNG)

**Comment by zgreen** [comment]
Looks like a `text-size-adjust` issue

**Comment by matt-bernhardt** [comment]
As I recall, there may have been an issue with div.whatami slipping up to the right of div.mitlibrarysearchform - which pushes the "What am I searching" block to the right as it tries to maintain position. Looking at the code now, I wonder why div.whatami is only clear:right rather than clear:both? That may resolve the most visible problem - although in each of the screenshots above, something has caused the Search button to slip down onto the next line, and there are other font size issues as well in the first and third images.

**Comment by zgreen** [comment]
```
div.whatami {
clear: both;
margin-top: 0;
width: auto;
}
```

and

`-webkit-text-size-adjust: 100%; /* Corrects odd font-size behavior in iOS Safari */`

seems to correct the font-size problem and float issue. Fix is on http://libraries-dev.mit.edu/.

Will check on the Search button.

**Comment by zgreen** [comment]
Also had to add

```
.floatwrapper .radiorow:last-of-type {
  margin-bottom: 1em;
}
```

in order to prevent div.whatami from bumping up against the bottom of the last .radiorow

**Comment by matt-bernhardt** [comment]
Looks good to me, but I'm not looking at it on an iOS device. Good catch on the bottom margin.

**Comment by zgreen** [comment]
Looks like the UA stylesheet of iOS Safari uses `em` units for padding on all `input` elements, (as opposed to the UA stylesheet for desktop browsers, most/all of which still seem to use pixels for padding on `input` elements).

Adding `padding-right: 0;` to `div.mitlibrarysearchform input.searchtext` seems to solve the problem. Search button already has a `margin-left: 5px` so it won't bump against the the search text box. Uploaded to http://libraries-dev.mit.edu/

@darcyduke do you want to check this out on your iphone? I've got the iOS simulator running on my machine, but always good to check this stuff out on the _actual_ device in question.

**Comment by zgreen** [comment]
Also, @matt-bernhardt can you have a look?

**Comment by darcyduke** [comment]
Most things are now displaying fine on http://libraries-dev.mit.edu/ on my iPhone.  The one item that still looks a bit amiss is the first tab seems to hang low over “Library Services” (and I presume would hang over an alert).

Thanks Zach.

Darcy

**Comment by zgreen** [comment]
Looks like setting `clear: both` on `div.whatami` makes

```
.floatwrapper .radiorow:last-of-type {
  margin-bottom: 1em;
}
```

unnecessary. `div.whatami` crowds the last radio button on the first search tab _a little_ but I don't think it looks bad. Changes on http://libraries-dev.mit.edu/

![ios simulator screen shot jan 10 2014 10 40 28 am](https://f.cloud.github.com/assets/1700355/1888462/f872894e-7a0d-11e3-9a09-f22136b32e3e.png)

Have a look @darcyduke @matt-bernhardt

**Comment by matt-bernhardt** [comment]
I'm looking at the page on the DLAD iPad right now, and seeing no problems. But, I'm not sure there would have been problems on a 10-inch screen beforehand.

**Comment by darcyduke** [comment]
I think it looks fine.  Great in fact!  Thanks Zach.

**Comment by zgreen** [comment]
Alright, I am going to make these changes to the homepage CSS (which is currently outside this repo) unless there are any objections @matt-bernhardt @darcyduke.

**Comment by darcyduke** [comment]
Full speed ahead!

**Comment by matt-bernhardt** [comment]
No objections here - godspeed :-)
